### ISSUE TITLE
Annual change in CO2 - preset chart

### ISSUE THREAD

**Issue by ledpup** [ledpup/ClimateExplorer#106]

**Comment by ledpup** [comment]
A chart of the difference between the max and min value for the year

**Comment by ledpup** [comment]
@acha11 This will be a DifferenceBetweenTwoSeries right? I suspect it'll need some extra coding though to get it working.

**Comment by acha11** [comment]
> @acha11 This will be a DifferenceBetweenTwoSeries right? I suspect it'll need some extra coding though to get it working.

DifferenceBetweenTwoSeries wouldn't work for this - it's very early in the pipeline, working at the raw data level (pre-aggregation), subtracting the raw value from one data source series from the raw value for another.

We'd need something similar to DifferenceBetweenTwoSeries, except that it'd apply later in the pipeline (at the very end, I think). 

We need to apply an aggregate function to calculate max CO2 at year bin size to generate one series, then (on another series) aggregate to calculate min CO2 at year bin size to generate a second series, and then subtract one from the other.

So it'd be a new pipeline phase that would combine the output of two BuildDataSetFromDataPoints() results, subtracting one from the other.

That'd involve extending BuildDataSet() - instead of taking just one copy of everything in PostDataSetsRequestBody, it'd need to optionally take a second copy. The first one in this case would be "from the monthly raw CO2 data, bin by year and take max", and the second would be "from the monthyl raw CO2 data, bin by year and take min".

**Comment by acha11** [comment]
Could we call this "Annual CO2 range" rather than "change"? "Change" suggests to me that the value for 2022 would be the difference between the 2022 and 2021 values, rather than the min value in 2022 and the max value in 2022.
